apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydeploy-pv-storage
  labels:
    app: mydeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi